### ISSUE TITLE
sqlitedict Error

### ISSUE THREAD

**Issue by janakal** [piskvorky/gensim-simserver#7]
When I run your script "test_simserver.py", I get many errors like the following one:
***ERROR : sqlitedict:285 : terminate(MainThread) : failed to delete /var/folders/19/c7lgjphn33d40rf_0p24rf9r0000gp/T/sqldictbb63df
Traceback (most recent call last):
  File "build/bdist.macosx-10.5-x86_64/egg/sqlitedict.py", line 283, in terminate
    os.remove(self.filename)
OSError: [Errno 2] No such file or directory: '/var/folders/19/c7lgjphn33d40rf_0p24rf9r0000gp/T/sqldictbb63df'***
 
At the end, I also get Exception Attribute Errors, like:
***Exception AttributeError: "'SessionServer' object has no attribute 'lock_update'" in <  bound method SessionServer.__del__ of < simserver.simserver.SessionServer object at 0x1050cedd0 > > ignored***

Hereafter is the configuration of python and required libraries:
+ python: 2.7.11
+ gensim: 0.12.4
+ sqlitedict: 1.4.0

Thank you in advance for your assistance.

**Comment by piskvorky** [comment]
Unfortunately simserver is no longer support as open source, it wasn't viable. We now offer commercial services in this "document similarity space": http://rare-technologies.com
